### ISSUE TITLE
"live-bitfinex" environment in lean.json faces issue with unknown data-queue-handler?

### ISSUE THREAD

**Issue by lucasbrynte** [QuantConnect/lean-cli#128] opened 2022-08-17 09:41 UTC
Hi!

The most recent lean.json config template provided by Lean CLI seems to contain the entry `"data-queue-handler": [ "BitfinexBrokerage" ],` for live trading with Bitfinex. However, I seem to get an error related to this when attempting local live trading in non-interactive mode.

I'm using the following configuration:
```
      // real brokerage implementations require the BrokerageTransactionHandler
      "live-mode-brokerage": "BitfinexBrokerage",
      "data-queue-handler": [ "BitfinexBrokerage" ],
      "setup-handler": "QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler",
      "result-handler": "QuantConnect.Lean.Engine.Results.LiveTradingResultHandler",
      "data-feed-handler": "QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed",
      "real-time-handler": "QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler",
      "transaction-handler": "QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler",
      "history-provider": [ "BrokerageHistoryProvider", "SubscriptionDataReaderHistoryProvider" ]

```

And receive the following error log:
```
20220817 09:18:20.135 TRACE:: Config.Get(): Configuration key not found. Key: job-organization-id - Using default value:
20220817 09:18:24.848 ERROR:: JobQueue.NextJob(): Error resolving BrokerageData for live job for brokerage BitfinexBrokerage System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantConnect.Util.Composer.Single[T](Func`2 predicate) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/Composer.cs:line 176
   at QuantConnect.Queues.JobQueue.NextJob(String& location) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Queues/JobQueue.cs:line 101
20220817 09:18:24.860 TRACE:: JobQueue.NextJob(): Not able to fetch data handler factory with name: BitfinexBrokerage
20220817 09:18:24.861 TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20220817 09:18:24.864 TRACE:: Config.GetValue(): streamed-chart-limit - Using default value: 12
20220817 09:18:24.864 TRACE:: Config.GetValue(): streamed-chart-group-size - Using default value: 3
20220817 09:18:24.930 TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20220817 09:18:24.932 TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20220817 09:18:24.971 TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20220817 09:18:24.979 TRACE:: Config.GetValue(): consumer-batching-timeout-ms - Using default value: 0
20220817 09:18:25.546 TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
20220817 09:18:25.551 TRACE:: PythonInitializer.Initialize(): start...
PythonEngine.Initialize(): clr GetManifestResourceStream...
20220817 09:18:26.196 TRACE:: PythonInitializer.Initialize(): ended
20220817 09:18:26.235 TRACE:: AlgorithmPythonWrapper(): Python version 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:25:33)
[GCC 7.3.0]: Importing python module main
20220817 09:18:41.196 TRACE:: AlgorithmPythonWrapper(): main successfully imported.
20220817 09:18:41.226 TRACE:: AlgorithmPythonWrapper(): Creating IAlgorithm instance.
20220817 09:18:41.265 TRACE:: Config.GetValue(): api-data-update-period - Using default value: 1
20220817 09:18:41.663 TRACE:: Config.GetValue(): mute-python-library-logging - Using default value: True
20220817 09:18:41.801 TRACE:: LocalObjectStore.Initialize(): Storage Root: /Storage/QCAlgorithm. StorageFileCount 9999999. StorageLimitMB 9999999
20220817 09:18:41.803 TRACE:: LiveTradingDataFeed.GetDataChannelProvider(): will use DataChannelProvider
20220817 09:18:41.808 ERROR:: Engine.Run():  System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantConnect.Util.Composer.Single[T](Func`2 predicate) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Util/Composer.cs:line 176
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.CreateBrokerage(AlgorithmNodePacket algorithmNodePacket, IAlgorithm uninitializedAlgorithm, IBrokerageFactory& factory) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BrokerageSetupHandler.cs:line 128
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Engine.cs:line 130
20220817 09:18:42.063 TRACE:: JOB HANDLERS:
20220817 09:18:42.063 TRACE::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed
20220817 09:18:42.063 TRACE::          Setup:        QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler
20220817 09:18:42.063 TRACE::          RealTime:     QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler
20220817 09:18:42.063 TRACE::          Results:      QuantConnect.Lean.Engine.Results.LiveTradingResultHandler
20220817 09:18:42.063 TRACE::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler
20220817 09:18:42.063 TRACE::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20220817 09:18:42.063 TRACE::          ObjectStore:  QuantConnect.Lean.Engine.Storage.LocalObjectStore
20220817 09:18:42.064 TRACE::          Brokerage:
20220817 09:18:42.066 TRACE:: DefaultAlphaHandler.Exit(): Exiting...
20220817 09:18:42.081 TRACE:: DefaultAlphaHandler.Exit(): Ended
```

As can be seen by the end of the error log, the Brokerage does not seem to have loaded properly. Perhaps this is simply a consequence of not being able to choose the data-queue-handler..?

I have also attempted deploying in interactive mode, and do not seem to get the same issue (and the Brokerage handler then does appear in the printed list from which it is otherwise missing). In this case I get the following lines printed out right after going through the interactive steps:
```
Package source with Name: Package source 1 added successfully.
The template "Solution File" was created successfully.
The template "Class Library" was created successfully.
  Determining projects to restore...
  Writing /tmp/tmpGOmgo6.tmp
info : Adding PackageReference for package 'QuantConnect.BitfinexBrokerage' into project '/ModulesProject/ModulesProject.csproj'.
info : Restoring packages for /ModulesProject/ModulesProject.csproj...
info : Installed QuantConnect.BitfinexBrokerage 2.5.14441 from /Modules with content hash 740LZw8ehDVA3La1irr8Y9MlyBWDHsTaL7q503xb20VGZN4/zNuv703ZaO4YtNVBL1ojT/B5ExXJosmchPzBUg==.
info : Package 'QuantConnect.BitfinexBrokerage' is compatible with all the specified frameworks in project '/ModulesProject/ModulesProject.csproj'.
info : PackageReference for package 'QuantConnect.BitfinexBrokerage' version '2.5.14441' added to file '/ModulesProject/ModulesProject.csproj'.
info : Generating MSBuild file /Compile/obj/ModulesProject/ModulesProject.csproj.nuget.g.props.
info : Generating MSBuild file /Compile/obj/ModulesProject/ModulesProject.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: /Compile/obj/ModulesProject/project.assets.json
log  : Restored /ModulesProject/ModulesProject.csproj (in 1.81 sec).
  Determining projects to restore...
  Writing /tmp/tmpO2w94j.tmp
info : Adding PackageReference for package 'QuantConnect.BitfinexBrokerage.ToolBox' into project '/ModulesProject/ModulesProject.csproj'.
info : Restoring packages for /ModulesProject/ModulesProject.csproj...
info : Installed QuantConnect.BitfinexBrokerage.ToolBox 2.5.14441 from /Modules with content hash sdxjFzOLf0hpYvwMJz+FeqlO6rsqPu7DIiR5G4ukrUapDPwxv1iKobZuaXHCsG5zXrOXeRXMjw4ls/CdmwDaeQ==.
info : Package 'QuantConnect.BitfinexBrokerage.ToolBox' is compatible with all the specified frameworks in project '/ModulesProject/ModulesProject.csproj'.
info : PackageReference for package 'QuantConnect.BitfinexBrokerage.ToolBox' version '2.5.14441' added to file '/ModulesProject/ModulesProject.csproj'.
info : Writing assets file to disk. Path: /Compile/obj/ModulesProject/project.assets.json
log  : Restored /ModulesProject/ModulesProject.csproj (in 3.87 sec).
```
This does perhaps suggest that I for some reason only manage to acquire the Bitfinex Module when using the interactive mode, and perhaps even that this is the root cause to the data-queue-handler issue..?

Although I don't get the same issue in interactive mode, I do however face another runtime error: (although I am unsure whether it is related)
```
20220817 09:33:35.235 TRACE:: WebSocketClientWrapper connection task started: wss://api.bitfinex.com/ws/2
20220817 09:33:35.235 TRACE:: WebSocketClientWrapper.HandleConnection(wss://api.bitfinex.com/ws/2): Connecting...
20220817 09:33:35.513 TRACE:: Debug: Launching analysis for L-3837832444 with LEAN Engine v2.5.0.0
20220817 09:33:40.480 TRACE:: WebSocketClientWrapper.OnOpen(): Connection opened (IsOpen:True, State:Open): wss://api.bitfinex.com/ws/2
20220817 09:33:40.489 TRACE:: BrokerageMultiWebSocketSubscriptionManager.GetWebSocketForSymbol(): added symbol: BTCUSD to websocket: 60695133 - Count: 1
20220817 09:33:40.567 TRACE:: BitfinexBrokerage.OnSubscribe(): Channel subscribed: Id:326212 BTCUSD/trades
20220817 09:33:42.610 TRACE:: BitfinexBrokerage.OnSubscribe(): Channel subscribed: Id:335788 BTCUSD/book
20220817 09:33:42.622 TRACE:: DataManager.AddSubscription(): Added BTCUSD,#0,BTCUSD,Hour,TradeBar,Trade,Adjusted,OpenInterest. Start: 7/30/2022 9:00:00 AM. End: 12/31/2050 12:00:00 AM
20220817 09:33:42.633 TRACE:: DataManager.AddSubscription(): Added BTCUSD,#0,BTCUSD,Minute,TradeBar,Trade,Adjusted,OpenInterest,Internal. Start: 8/17/2022 9:33:42 AM. End: 12/31/2050 12:00:00 AM
20220817 09:33:42.634 TRACE:: DataManager.AddSubscription(): Added BTCUSD,#0,BTCUSD,Hour,QuoteBar,Quote,Adjusted,OpenInterest. Start: 7/30/2022 9:00:00 AM. End: 12/31/2050 12:00:00 AM
20220817 09:33:42.635 TRACE:: DataManager.AddSubscription(): Added BTCUSD,#0,BTCUSD,Minute,QuoteBar,Quote,Adjusted,OpenInterest,Internal. Start: 8/17/2022 9:33:42 AM. End: 12/31/2050 12:00:00 AM
20220817 09:33:42.924 ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 7/30/2022 9:00:00 AM UTC. Context: LiveSynchronizer System.Exception: BitfinexBrokerage.GetHistory: request failed: [500]
Internal Server Error, Content: ["error",10020,"time_interval: invalid"], ErrorMessage:
   at QuantConnect.Brokerages.Bitfinex.BitfinexBrokerage.GetHistory(HistoryRequest request)+c()
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SubscriptionDataEnumerator.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SubscriptionDataEnumerator.cs:line 84
   at QuantConnect.Lean.Engine.DataFeeds.Subscription.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Subscription.cs:line 209
   at QuantConnect.Lean.Engine.HistoricalData.SynchronizingHistoryProvider.CreateSliceEnumerableFromSubscriptions(List`1 subscriptions, DateTimeZone sliceTimeZone)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/HistoricalData/SynchronizingHistoryProvider.cs:line 59
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SynchronizingEnumerator`1.GetBruteForceMethod(IEnumerator`1[] enumerators)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SynchronizingEnumerator.cs:line 143
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SynchronizingEnumerator`1.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SynchronizingEnumerator.cs:line 93
   at QuantConnect.Lean.Engine.HistoricalData.HistoryProviderManager.GetHistory(IEnumerable`1 requests, DateTimeZone sliceTimeZone)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/HistoricalData/HistoryProviderManager.cs:line 120
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.FilterEnumerator`1.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/FilterEnumerator.cs:line 57
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.ConcatEnumerator.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/ConcatEnumerator.cs:line 75
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.FillForwardEnumerator.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/FillForwardEnumerator.cs:line 117
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.FilterEnumerator`1.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/FilterEnumerator.cs:line 57
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.ConcatEnumerator.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/ConcatEnumerator.cs:line 75
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SubscriptionDataEnumerator.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SubscriptionDataEnumerator.cs:line 84
   at QuantConnect.Lean.Engine.DataFeeds.Subscription.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Subscription.cs:line 209
   at QuantConnect.Lean.Engine.DataFeeds.SubscriptionSynchronizer.Sync(IEnumerable`1 subscriptions, CancellationToken cancellationToken)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/SubscriptionSynchronizer.cs:line 116
   at QuantConnect.Lean.Engine.DataFeeds.LiveSynchronizer.StreamData(CancellationToken cancellationToken)+MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/LiveSynchronizer.cs:line 118
20220817 09:33:43.094 ERROR:: AlgorithmManager.Run(): Stopping, encountered a runtime error at 7/30/2022 9:00:00 AM UTC.
20220817 09:33:43.095 TRACE:: Engine.Run(): Exiting Algorithm Manager
20220817 09:33:43.096 TRACE:: LiveTradingDataFeed.Exit(): Start. Setting cancellation token...
20220817 09:33:43.097 TRACE:: StopSafely(): waiting for 'CustomDataExchange' thread to stop...
20220817 09:33:43.097 TRACE:: BaseDataExchange(CustomDataExchange).ConsumeQueue(): Exiting...
20220817 09:33:43.097 TRACE:: LiveTradingDataFeed.Exit(): Exit Finished.
20220817 09:33:43.098 TRACE:: FileSystemDataFeed.Exit(): Start. Setting cancellation token...
20220817 09:33:43.100 TRACE:: FileSystemDataFeed.Exit(): Exit Finished.
20220817 09:33:43.100 TRACE:: Engine.Run(): Sending runtime error to user...
20220817 09:33:43.101 TRACE:: StopSafely(): waiting for 'Transaction Thread' thread to stop...
20220817 09:33:43.102 TRACE:: BrokerageTransactionHandler.Run(): Ending Thread...
20220817 09:33:43.111 TRACE:: DataManager.RemoveSubscription(): Removed BTCUSD,#0,BTCUSD,Minute,TradeBar,Trade,Adjusted,OpenInterest,Internal
20220817 09:33:43.113 TRACE:: DataManager.RemoveSubscription(): Removed BTCUSD,#0,BTCUSD,Hour,TradeBar,Trade,Adjusted,OpenInterest
20220817 09:33:43.114 TRACE:: DataManager.RemoveSubscription(): Removed QC-UNIVERSE-USERDEFINED-BITFINEX-CRYPTO,#0,QC-UNIVERSE-USERDEFINED-BITFINEX-CRYPTO,Hour,TradeBar,Trade,Adjusted,OpenInterest,Internal
20220817 09:33:43.114 TRACE:: DataManager.RemoveSubscription(): Removed BTCUSD,#0,BTCUSD,Minute,QuoteBar,Quote,Adjusted,OpenInterest,Internal
20220817 09:33:43.115 TRACE:: BrokerageMultiWebSocketSubscriptionManager.Unsubscribe(): BTCUSD
20220817 09:33:43.180 TRACE:: DataManager.RemoveSubscription(): Removed BTCUSD,#0,BTCUSD,Hour,QuoteBar,Quote,Adjusted,OpenInterest
20220817 09:33:43.181 TRACE:: StopSafely(): waiting for 'Isolator Thread' thread to stop...
20220817 09:33:43.183 TRACE:: StopSafely(): waiting for 'RealTimeScheduleEventService' thread to stop...
20220817 09:33:43.185 TRACE:: DefaultAlphaHandler.Exit(): Exiting...
20220817 09:33:43.192 TRACE:: DefaultAlphaHandler.Exit(): Ended
20220817 09:33:43.204 TRACE:: Log: Runtime Error: BitfinexBrokerage.GetHistory: request failed: [500] Internal Server Error, Content: ["error",10020,"time_interval: invalid"], ErrorMessage:  in SubscriptionDataEnumerator.cs:line 84
20220817 09:33:43.204 ERROR:: Runtime Error: BitfinexBrokerage.GetHistory: request failed: [500] Internal Server Error, Content: ["error",10020,"time_interval: invalid"], ErrorMessage:  in SubscriptionDataEnumerator.cs:line 84
 BitfinexBrokerage.GetHistory: request failed: [500] Internal Server Error, Content: ["error",10020,"time_interval: invalid"], ErrorMessage:  in SubscriptionDataEnumerator.cs:line 84

```

**Comment by lucasbrynte** [comment] 2022-08-18 10:45
I see now that the latest lean-cli version is 1.0.101, and the latest docker image ID is 378a6afdc2f2. Rerunning with these versions makes no difference and results in the following output log files:
[log-issue1-leancli_1_0_101.txt](https://github.com/QuantConnect/lean-cli/files/9372749/log-issue1-leancli_1_0_101.txt)
[log-issue2-leancli_1_0_101.txt](https://github.com/QuantConnect/lean-cli/files/9372750/log-issue2-leancli_1_0_101.txt)

**Comment by rjra2611** [comment] 2022-08-18 23:17
Hey Lucas,

We released a new version of the lean-cli `pip install lean==1.0.102` with added debugging logs to better assess your issue. 
Can you please do a re-run for both your issues with a `--verbose`  flag added to `lean live`  command like `lean live <project> --brokerage  <brokerage> --data-feed <data-feed> --verbose` and share the resultant logs?

Thanks,
Ronit

**Comment by lucasbrynte** [comment] 2022-08-19 08:45
Hi Ronit!

I updated lean-cli to 1.0.102, and the Docker image to ID 4fd6aba4b253, although I'm not sure how relevant the latter is..?

Here are the resulting log files:
[log-issue1-leancli_1_0_102-verbose.txt](https://github.com/QuantConnect/lean-cli/files/9380551/log-issue1-leancli_1_0_102-verbose.txt)
[log-issue2-leancli_1_0_102-verbose.txt](https://github.com/QuantConnect/lean-cli/files/9380552/log-issue2-leancli_1_0_102-verbose.txt)

//Lucas

**Comment by rjra2611** [comment] 2022-08-19 10:40
Hey Lucas,

Applogies for the constant back and forth. 

When sharing the logs, could you copy paste the console stdout where the debug logs are getting printed when using the ` --verbose` option

Please make sure to copy from the first line till the end for both the issues. 

PFA, the sample log file and image

[sample_log.txt](https://github.com/QuantConnect/lean-cli/files/9381466/sample_log.txt)

![image](https://user-images.githubusercontent.com/28739120/185601210-3683a639-5b55-4575-9f80-22ad77c22e04.png)


Thanks,
Ronit

**Comment by lucasbrynte** [comment] 2022-08-19 12:02
Hi Ronit,

Here are the requested outputs:
[stdout-issue1-leancli_1_0_102-verbose.txt](https://github.com/QuantConnect/lean-cli/files/9381877/stdout-issue1-leancli_1_0_102-verbose.txt)
[stdout-issue2-leancli_1_0_102-verbose.txt](https://github.com/QuantConnect/lean-cli/files/9381878/stdout-issue2-leancli_1_0_102-verbose.txt)

In the second (interactive) case, note that with the verbose option the API key & secret are revealed on the line starting with `interactive: required_properties_value:`. For obvious reasons I have made sure to conceal this information, but also wanted to highlight the potential caveat. If such logs are required to be shared publicly in the future, I think it would be good to explicitly point this out to other users.

//Lucas

**Comment by lucasbrynte** [comment] 2022-08-19 12:04
Sorry, here are the files:
[stdout-issue1-leancli_1_0_102-verbose.txt](https://github.com/QuantConnect/lean-cli/files/9381936/stdout-issue1-leancli_1_0_102-verbose.txt)
[stdout-issue2-leancli_1_0_102-verbose.txt](https://github.com/QuantConnect/lean-cli/files/9381938/stdout-issue2-leancli_1_0_102-verbose.txt)

**Comment by lucasbrynte** [comment] 2022-08-22 19:36
Thank you for the update to the code base! I've rerun the experiment with lean-cli version 1.0.103, and it seems to resolve my first issue nicely.

I do however end up with the second issue discussed above, no matter whether I'm using interactive mode or not. Was the PR aiming to resolve that issue too? Should I perhaps create a separate issue for it?

This is the stack trace printed (but you can also see it in the logs dumped above):
```
20220822 19:28:29.174 ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 8/4/2022 7:00:00 PM UTC. Context: LiveSynchronizer 
System.Exception: BitfinexBrokerage.GetHistory: request failed: [500] Internal Server Error, Content: ["error",10020,"time_interval: invalid"], ErrorMessage:
   at QuantConnect.Brokerages.Bitfinex.BitfinexBrokerage.GetHistory(HistoryRequest request)+c()
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SubscriptionDataEnumerator.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SubscriptionDataEnumerator.cs:line 84
   at QuantConnect.Lean.Engine.DataFeeds.Subscription.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Subscription.cs:line 209
   at QuantConnect.Lean.Engine.HistoricalData.SynchronizingHistoryProvider.CreateSliceEnumerableFromSubscriptions(List`1 subscriptions, DateTimeZone sliceTimeZone)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/HistoricalData/SynchronizingHistoryProvider.cs:line 59
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SynchronizingEnumerator`1.GetBruteForceMethod(IEnumerator`1[] enumerators)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SynchronizingEnumerator.cs:line 143
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SynchronizingEnumerator`1.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SynchronizingEnumerator.cs:line 93
   at QuantConnect.Lean.Engine.HistoricalData.HistoryProviderManager.GetHistory(IEnumerable`1 requests, DateTimeZone sliceTimeZone)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/HistoricalData/HistoryProviderManager.cs:line 120
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.FilterEnumerator`1.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/FilterEnumerator.cs:line 57
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.ConcatEnumerator.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/ConcatEnumerator.cs:line 75
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.FillForwardEnumerator.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/FillForwardEnumerator.cs:line 117
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.FilterEnumerator`1.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/FilterEnumerator.cs:line 57
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.ConcatEnumerator.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/ConcatEnumerator.cs:line 75
   at QuantConnect.Lean.Engine.DataFeeds.Enumerators.SubscriptionDataEnumerator.MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Enumerators/SubscriptionDataEnumerator.cs:line 84
   at QuantConnect.Lean.Engine.DataFeeds.Subscription.MoveNext() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/Subscription.cs:line 209
   at QuantConnect.Lean.Engine.DataFeeds.SubscriptionSynchronizer.Sync(IEnumerable`1 subscriptions, CancellationToken cancellationToken)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/SubscriptionSynchronizer.cs:line 116
   at QuantConnect.Lean.Engine.DataFeeds.LiveSynchronizer.StreamData(CancellationToken cancellationToken)+MoveNext() in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/LiveSynchronizer.cs:line 118
20220822 19:28:29.458 ERROR:: AlgorithmManager.Run(): Stopping, encountered a runtime error at 8/4/2022 7:00:00 PM UTC.

```

**Comment by Martin-Molinero** [comment] 2022-08-22 19:54
Hey @lucasbrynte!
Happy to hear the first issue was fixed, regarding this second issue, it's a bug in the brokerage module itself, not the lean CLI.
I'll reopen this issue so we can take a look at it 👍.
Do you mind sharing the minimum algorithm reproducing the issue? based on the stack trace it looks like some resolution isn't supported by the bitfinex history provider

**Comment by lucasbrynte** [comment] 2022-08-22 20:41
Hi @Martin-Molinero, and thanks for the clarification.

Please find attached a minimal algorithm reproducing the issue. Hourly resolution is used.
[main.py.txt](https://github.com/QuantConnect/lean-cli/files/9397479/main.py.txt)

Best,
Lucas

**Comment by lucasbrynte** [comment] 2022-08-24 19:03
I have now expanded on the remaining issue(s) in greater depth in a new issue in the Lean repo:

https://github.com/QuantConnect/Lean/issues/6578

I hope this helps resolving it, and that the brokerage module will soon be usable.

Best,
Lucas

**Comment by Martin-Molinero** [comment] 2022-08-24 20:20
Thanks @lucasbrynte! We will look into it ASAP. Will close this issue now

**Closed by Martin-Molinero** 2022-08-24 20:20 UTC
Labels: bug
