### ISSUE TITLE
The backtest shows partial results before job completed

### ISSUE THREAD

**Issue by lifelonginvestor** [QuantConnect/lean-cli#460] opened 2024-05-21 10:59 UTC
The backtest randomly shows partial results as below, looks like it stopped/aborted before job completed

```
Started backtest named 'Muscular Yellow Rhinoceros' for project 'liats'
Backtest url: https://www.quantconnect.com/project/17908729/c383715ebd9e347007c41a56299423b0
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
┌────────────────────────────┬─────────────┬────────────┬─────────────┐
│ Statistic                  │ Value       │ Statistic  │ Value       │
├────────────────────────────┼─────────────┼────────────┼─────────────┤
│ Equity                     │ $100,670.36 │ Fees       │ -$24.70     │
│ Holdings                   │ $32,250.00  │ Net Profit │ $575.30     │
│ Probabilistic Sharpe Ratio │ 0%          │ Return     │ 0.57 %      │
│ Unrealized                 │ $-4.94      │ Volume     │ $163,400.00 │
└────────────────────────────┴─────────────┴────────────┴─────────────┘
Backtest id: c383715ebd9e347007c41a56299423b0
```

**Comment by Martin-Molinero** [comment] 2024-05-21 12:46
Hey @lifelonginvestor! Sorry we can't reproduce the issue, please contact support so we can debug this case further

**Comment by Martin-Molinero** [comment] 2024-08-15 13:19
Closing for now until we can reproduce the issue

**Closed by Martin-Molinero** 2024-08-15 13:19 UTC
