### ISSUE TITLE
pywin32 issue on install

### ISSUE THREAD

**Issue by undershot1** [QuantConnect/lean-cli#68] opened 2022-02-20 11:49 UTC
I'm trying to install lean and have come across an issue seemingly related to pywin32.

I initially installed the package simply using pip and my base anaconda3 package, but was getting an install of version 0.1.2. When I specify version 1.0.78, I get the below error...

```
ERROR: Cannot install lean because these package versions have conflicting dependencies.

The conflict is caused by:
    docker 4.4.4 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.3 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.2 depends on pywin32==227; sys_platform == "win32"
    docker 4.4.1 depends on pywin32==227; sys_platform == "win32"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

This error states that the requirements.txt (or however pip works) requires bersion 227 of pywin32 installed. I've tried pip install pywin32==227, but apparently this version is no longer available.

Can anyone provide help on this?

**Comment by punitarani** [comment] 2022-03-13 20:41
I am having the same issue. 

The setup.py indicates that lean-cli requires docker~=4.4.1, whereas the latest docker version is 5.0.3. Docker 4.4.1 only supports pywin32 227 which is not supported for Python >=3.10.

This problem could be fixed by updating the setup.py to reflect the latest docker version.

**Comment by Martin-Molinero** [comment] 2022-04-20 16:35
Closing as duplicate of https://github.com/QuantConnect/lean-cli/issues/54

**Closed by Martin-Molinero** 2022-04-20 16:35 UTC
