### ISSUE TITLE
probably an issue with json library

### ISSUE THREAD

**Issue by SergejGorev** [QuantConnect/lean-cli#10] opened 2021-06-03 09:10 UTC
lean is initialized, i am logged in, but not able to download any data.

![image](https://user-images.githubusercontent.com/57412519/120618580-81949b00-c45b-11eb-948c-88f94842b4ee.png)

Based on my experience, this error points to a json library which is not able to handle comments in the json file.

**Comment by aliabdoli** [comment] 2021-06-03 09:15
exact same error. I also tried daily (to download daily by this code)
`lean data download forex --ticker eurusd --market fxcm --resolution daily --overwrite`

- ubuntu 20.4
- anaconda3

I got this error:

```[1/1] Downloading forex/fxcm/daily/eurusd.zip
POST https://www.quantconnect.com/api/v2/data/read with data {'format': 'link', 'type': 'forex', 'ticker': 'eurusd', 'market': 'fxcm', 'resolution': 'daily'}
Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/main.py", line 39, in main
    lean.main(standalone_mode=False)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/click.py", line 80, in invoke
    result = super().invoke(ctx)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/commands/data/download/forex.py", line 83, in forex
    overwrite=overwrite)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/cloud/data_downloader.py", line 93, in download_data
    self._download_files(files, overwrite)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/cloud/data_downloader.py", line 107, in _download_files
    self._download_file(file, overwrite, data_dir)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/cloud/data_downloader.py", line 134, in _download_file
    raise error
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/cloud/data_downloader.py", line 127, in _download_file
    file.date)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/api/data_client.py", line 57, in get_link
    data = self._api.post("data/read", parameters)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/api/api_client.py", line 83, in post
    return self._request("post", endpoint, options)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/api/api_client.py", line 128, in _request
    return self._parse_response(response)
  File "/home/ali/anaconda3/envs/algo-trading/lib/python3.7/site-packages/lean/components/api/api_client.py", line 147, in _parse_response
    raise RequestFailedError(response, "\n".join(data["errors"]))
lean.models.errors.RequestFailedError: Organization not found
Error: Organization not found
```

**Comment by SergejGorev** [comment] 2021-06-03 09:23
Adding more depth into it. But i dont know if its me or lean-cli

```
 ~/A/QC ❯❯❯ lean data download forex --ticker eurusd --market oanda --resolution minute --start 20000101 --end 20220101 --verbose                                                                           (algo) 
Traceback (most recent call last):
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/main.py", line 39, in main
    lean.main(standalone_mode=False)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/click.py", line 80, in invoke
    result = super().invoke(ctx)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/commands/data/download/forex.py", line 83, in forex
    overwrite=overwrite)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/components/cloud/data_downloader.py", line 75, in download_data
    dates = self._get_dates_with_data(security_type, market, ticker, start, end)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/components/cloud/data_downloader.py", line 167, in _get_dates_with_data
    entry = self._market_hours_database.get_entry(security_type, market, symbol)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/components/util/market_hours_database.py", line 42, in get_entry
    entries = self._get_all_entries()
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/site-packages/lean/components/util/market_hours_database.py", line 60, in _get_all_entries
    market_hours_database = json.loads(market_hours_database_path.read_text(encoding="utf-8"))
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/xetra/miniconda3/envs/algo/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 29560 column 5 (char 738672)
Error: Expecting property name enclosed in double quotes: line 29560 column 5 (char 738672)
```

**Comment by jmerle** [comment] 2021-06-03 14:42
Hi Sergej,

I'm sorry for the inconvenience. We're currently working on improving the data downloading part of the CLI and of LEAN, and while some of these changes have already gone to production others haven't. This causes the "Organization not found" error you're seeing. A new version of the CLI will be available in 1-2 days. This version fixes the error, makes downloading data more user-friendly and supports more than just CFD and Forex data.

The "Expecting property name enclosed in double quotes" error is indeed caused by using a JSON library which doesn't support comments and will also be fixed in the next version.

**Comment by jmerle** [comment] 2021-06-05 00:09
The new version of the CLI has been released. You can update using `pip install --upgrade lean`. In the new version the `lean data download cfd` and `lean data download forex` commands have been replaced with the `lean data download` command.

Note that CFD and Forex data is no longer free to download with the CLI, we now charge per file per download. You can see the complete list of available data and pricing in the [documentation](https://www.quantconnect.com/docs/v2/lean-cli/user-guides/local-data#03-QuantConnect-Data-Library), or by running the `lean data download` command and going through its interactive wizard (you are prompted for confirmation with a table showing the total price of the selected data before it starts downloading anything).

**Closed by jmerle** 2021-06-05 00:09 UTC
